export default {
  // Where to find the source design token JSON files (generated by the parser)
  source: ["tokens/**/*.json"],

  // Style Dictionary platforms definition – one for each output format target
  platforms: {
    // 1. CSS Custom Properties
    css: {
      transformGroup: "web",                   // Use web transforms (name/kebab, size/px, color/css):contentReference[oaicite:8]{index=8}
      buildPath: "build/",
      files: [{
        destination: "tokens.css",
        format: "css/variables",              // CSS :root variables format:contentReference[oaicite:9]{index=9}
        options: {
          // No outputReferences here, so aliases will be resolved to actual values in the CSS output by default
        }
      }]
    },

    // 2. Nested JSON
    json: {
      transformGroup: "web",
      buildPath: "build/",
      files: [{
        destination: "tokens.json",
        format: "json/nested"                 // Nested JSON format for structured tokens:contentReference[oaicite:10]{index=10}
      }]
    },

    // 3. SCSS Variables
    scss: {
      transformGroup: "web",                  // Also using web (which adds "px" to size values, etc.)
      buildPath: "build/",
      files: [{
        destination: "tokens.scss",
        format: "scss/variables",            // SCSS $variable declarations:contentReference[oaicite:11]{index=11}
        options: {
          outputReferences: false           // (Aliases resolved to values; set true if you prefer reference links in SCSS)
        }
      }]
    },

    // 4. JS and TS (TypeScript) exports
    js: {
      transformGroup: "js",                  // JS transform (uses name/pascal, size/rem, color/hex by default):contentReference[oaicite:12]{index=12}
      buildPath: "build/",
      files: [
        {
          destination: "tokens.js",
          format: "javascript/es6"          // ES6 module exporting each token as a constant:contentReference[oaicite:13]{index=13}:contentReference[oaicite:14]{index=14}
        },
        {
          destination: "tokens.d.ts",
          format: "typescript/es6-declarations"  // TypeScript declarations for the ES6 exports:contentReference[oaicite:15]{index=15}
        }
      ]
    },

    // 5. Android (XML resources)
    android: {
      transformGroup: "android",            // Android transforms (name/snake, color/hex8, size to dp/sp):contentReference[oaicite:16]{index=16}
      buildPath: "build/",
      files: [{
        destination: "tokens.xml",
        format: "android/resources",       // All tokens in one Android resource XML:contentReference[oaicite:17]{index=17}:contentReference[oaicite:18]{index=18}
        options: {
          // Using android/resources will auto-group tokens by type (colors, dimens, etc.) in the XML output
        }
      }]
    },

    // 6. iOS: Plist and Swift
    ios: {
      transformGroup: "ios",               // iOS Objective-C transforms (we'll use these for plist; naming handled in format)
      buildPath: "build/",
      files: [
        {
          destination: "tokens.plist",
          format: "ios/plist"             // Property list containing all tokens (for Objective-C usage)
        },
        {
          destination: "StyleDictionary.swift",
          format: "ios-swift/class.swift",  // Swift class with static let constants:contentReference[oaicite:19]{index=19}
          options: {
            className: "StyleDictionary",   // Name of the Swift class (public, with UIKit imported by default):contentReference[oaicite:20]{index=20}
            swiftLanguageVersion: 5        // (Optional) ensure compatibility with Swift 5
          }
        }
      ]
    }
  }
};
